name: storage_only_quarterhourly_fixed_price    # name of the optimization

hours_per_timestep: 0.25    # quarter hour timesteps

add_storage: True   # wether to add storage to optimization or not
allow_additional_pv: False    # wether to add pv system to optimization or not

auto_opt: False    # Wether to automatically start optizmization or not
solver: "gurobi"

verbose: True   # Wether to print optimization progress or not

##############
# timeseries #
##############
# name of the column where timestamps are provided (should be equal in all files)
# can be set to None if timestamps are not provided, we will then assume timestamps based on pattern
timestamp_column:

consumption_file_path: consumption.csv   # file path where consumption is stored as .csv
consumption_value_column: consumption                       # name of the column where consumption is provided

price_file_path:       # file path where prices are stored as .csv
price_value_column:                            # name of the column where prices are provided

postal_code:    # postal code for automtic pv generation calculation, leave empty for own timeseries
# if not provided, pv generation will be calculated with the following parameters
# value column needs to contain values from 0 (no pv generation) to 1 (max pv generation)
new_pv_file_path: # file path where pv generation is stored as .csv
new_pv_value_column:                                   # name of the column where pv generation is provided

################################
# storage (battery) parameters #
################################
storage_lifetime: 15    # storage lifetime in years
# taken from:
# "Energiespeicher - Bedarf, Technologien, Integration", Stadler Sterner 2017

storage_cost_per_kwh: 145   # storage capacity cost in euro per kwh capacity
# taken from:
# https://www.pem.rwth-aachen.de/cms/pem/der-lehrstuhl/presse-medien/aktuelle-meldungen/~bexlow/battery-monitor-2023-nachfrage-waechst/

max_storage_size_kwh:     # maximum available storage size in kWh (leave empty for infinite size)

storage_charge_efficiency: 0.9      # efficiency for charging storage
storage_discharge_efficiency: 0.9   # efficiency for discharging storage
# for round trip efficiency of 0.81
# taken from:
# https://www.sciencedirect.com/science/article/pii/S2352152X23027846

storage_charge_rate: 1      #
storage_discharge_rate: 1   #
# taken from:
# https://www.sciencedirect.com/science/article/pii/S2590116819300116

#################################
# storage (inverter) parameters #
#################################
inverter_efficiency: 0.95   # efficiency of the storage inverter
# taken from:
# https://www.sciencedirect.com/science/article/pii/S1364032116306712

inverter_lifetime: 15   # storage inverter lifetime in years
# taken from:
# 10.4229/WCPEC-82022-3DV.1.46 Bucher Joss

inverter_cost_per_kw: 180   # storage inverter cost in euro per kw
# taken from:
# https://www.sciencedirect.com/science/article/pii/S1876610216310736


########################
# PV system parameters #
########################
pv_system_lifetime: 30    # pv system lifetime in years
# taken from:
# https://www.mdpi.com/1996-1073/14/14/4278

pv_system_cost_per_kwp: 1250    # pv system cost in euro per kWpeak
# taken from:
# https://www.ise.fraunhofer.de/de/veroeffentlichungen/studien/studie-stromgestehungskosten-erneuerbare-energien.html

pv_system_kwp_per_m2: 0.4   # energy obtainable per area in kWpeak per m²
max_pv_system_size_kwp:   # maximum available pv system size in kWpeak (leave empty for infinite size)

#######################
# economic parameters #
#######################
overwrite_price_timeseries: True         # Wether to overwrite price timeseries or not
producer_energy_price: 0.15 # €/kWh     # energy price if sourced from supplier
# value for 2024 taken from:
# https://www.bdew.de/service/daten-und-grafiken/bdew-strompreisanalyse/
# https://de.statista.com/statistik/daten/studie/252029/umfrage/industriestrompreise-inkl-stromsteuer-in-deutschland/

grid_capacity_price: 130      # capacity price in euro to be paid yearly
grid_energy_price: 0.0460     # energy price in euro per kwh to be paid per kwh source from grid
# mean updated with historical inflation of cumulative 26.24% from:
# https://zenodo.org/records/13734730

interest_rate: 3    # interes rate in %
