services:
  database:
    image: timescale/timescaledb-ha:pg17
    container_name: psa_database
    restart: always
    user: root
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=psa
    ports:
      - "5432:5432"
    volumes:
      - ./data/database:/home/postgres/pgdata
      - ./docker_configs/init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    image: grafana/grafana-oss
    container_name: psa_dashboard
    restart: always
    ports:
      - "3000:3000"
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: "true"
    volumes:
      - ./docker_configs/grafana.ini:/etc/grafana/grafana.ini
      - ./docker_configs/datasources:/etc/grafana/provisioning/datasources
      - ./docker_configs/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker_configs/dashboard-definitions:/etc/grafana/provisioning/dashboard-definitions
