{
 "title": "Home",
 "time": { "from": "2023-01-01T00:00:00Z", "to": "2023-12-31T23:45:00Z" },
 "templating": {
  "list": [
   {
    "name": "opti_name",
    "label": "Optimization",
    "query": "SELECT DISTINCT(name) FROM input.parameters"
   }
  ]
 },
 "panels": [
  { "title": "Costs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total savings",
   "type": "stat",
   "description": "Total savings integrating saved capacity cost and storage system annuity.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "WITH orig_cap_costs AS (\n  SELECT max(consumption_kw) * (SELECT grid_capacity_price FROM input.parameters WHERE name = '$opti_name') AS orig_cap\n  FROM input.timeseries\n  WHERE name = '$opti_name'),\n  battery_system_cost AS (\n    SELECT storage_annuity_eur + inverter_annuity_eur AS bsc FROM output.eco WHERE name = '$opti_name'\n  )\nSELECT\n  (SELECT orig_cap FROM orig_cap_costs WHERE name = '$opti_name') - grid_capacity_costs_eur - (SELECT bsc FROM battery_system_cost WHERE name = '$opti_name') AS \"Total savings\"\nFROM output.eco WHERE name = '$opti_name'"
    }
   ]
  },
  {
   "title": "Capacity costs",
   "type": "stat",
   "description": "Capacity price to be paid to grid operator.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  max(consumption_kw) * (SELECT grid_capacity_price FROM input.parameters WHERE name = '$opti_name') AS \"Original\"\nFROM input.timeseries\nWHERE name = '$opti_name'"
    },
    {
     "rawSql": "SELECT grid_capacity_costs_eur AS \"Optimized\"\nFROM output.eco\nWHERE name = '$opti_name' "
    },
    {
     "rawSql": "SELECT (\n  SELECT max(consumption_kw) * (SELECT grid_capacity_price FROM input.parameters WHERE name = '$opti_name') AS \"Original\"\n  FROM input.timeseries\n  WHERE name = '$opti_name') - (\n    SELECT grid_capacity_costs_eur AS \"Optimized\"\n  FROM output.eco\n  WHERE name = '$opti_name' ) AS \"Savings\""
    }
   ]
  },
  {
   "title": "Storage system invest",
   "type": "stat",
   "description": "Investment needed for storage system.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  storage_invest_eur AS \"Storage\",\n  inverter_invest_eur AS \"Inverter\",\n  storage_invest_eur + inverter_invest_eur AS \"Total\"\nFROM output.eco \nWHERE name = '$opti_name'"
    }
   ]
  },
  {
   "title": "Storage system annuity",
   "type": "stat",
   "description": "Cost for storage system including battery and inverter as annuity",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "currencyEUR" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  storage_annuity_eur AS \"Storage\",\n  inverter_annuity_eur AS \"Inverter\",\n  storage_annuity_eur + inverter_annuity_eur AS \"Total\"\nFROM output.eco\nWHERE name = '$opti_name'"
    }
   ]
  },
  {
   "title": "Sizes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Max grid load",
     "type": "stat",
     "description": "Maximum load on grid.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "kwatt" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  max(grid_usage_kw) AS \"Optimized\",\n  max(consumption_kw) AS \"Default\"\nFROM output.timeseries\nWHERE name = '$opti_name'"
      }
     ]
    },
    {
     "title": "Battery system",
     "type": "stat",
     "description": "Size of battery system components.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT \n  storage_capacity_kwh AS \"Storage capacity [kWh]\",\n  inverter_capacity_kw AS \"Inverter capacity [kW]\"\nFROM output.tech\nWHERE name = '$opti_name'"
      }
     ]
    }
   ]
  },
  { "title": "Time series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Demand, grid and storage usage",
   "type": "timeseries",
   "description": "Demand, grid and storage (State of charge, charging, discharging) usage",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp,\n  grid_usage_kw AS \"Grid usage [kW]\",\n  consumption_kw AS \"Consumption [kW]\",\n  storage_charge_kw AS \"Storage charging [kW]\",\n  storage_discharge_kw AS \"Storage discharging [kW]\",\n  storage_soc_kwh AS \"Storage state of charge [kWh]\"\nFROM output.timeseries\nWHERE name = '$opti_name'"
    },
    {
     "rawSql": "SELECT \n  timestamp,\n  price_eur AS \"Price [Eur/kWh]\"\nFROM input.timeseries\nWHERE name = '$opti_name'"
    }
   ]
  },
  { "title": "Input parameters", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    name AS \"Name\",\n    hours_per_timestep AS \"Hours per timestep [h]\",\n    n_timesteps AS \"Number of timesteps\",\n    postal_code AS \"Postal code\",\n    add_storage AS \"Add storage\",\n    add_solar AS \"Add solar\",\n    producer_energy_price AS \"Producer energy price [Eur/kWh]\",\n    grid_capacity_price AS \"Grid capacity price [Eur/kW]\",\n    grid_energy_price AS \"Grid energy price [Eur/kWh]\",\n    pv_system_lifetime AS \"PV system lifetime [Years]\",\n    pv_system_cost_per_kwp AS \"PV system cost per kWp [Eur/kWp]\",\n    storage_lifetime AS \"Storage lifetime [Years]\",\n    storage_cost_per_kwh AS \"Storage cost per kWh [Eur/kWh]\",\n    inverter_cost_per_kw AS \"Inverter cost per kW [Eur/kW]\",\n    inverter_lifetime AS \"Inverter lifetime [Years]\",\n    interest_rate * 100 AS \"Interest rate [%]\",\n    max_storage_size_kwh AS \"Max storage size [kWh]\",\n    max_pv_system_size_kwp AS \"Max PV system size [kWp]\",\n    storage_charge_efficiency * 100 AS \"Storage charge efficiency [%]\",\n    storage_discharge_efficiency  * 100 AS \"Storage discharge efficiency [%]\",\n    storage_charge_rate AS \"Storage charge rate\",\n    storage_discharge_rate AS \"Storage discharge rate\",\n    inverter_efficiency * 100 AS \"Inverter efficiency [%]\",\n    pv_system_kwp_per_m2 AS \"PV system kWp per square meter [kWp/m²]\",\n    solver AS \"Solver\",\n    assumed_year AS \"Assumed year\",\n    leap_year::bool AS \"Is leap year\"\nFROM input.parameters\nWHERE name = '$opti_name'"
    }
   ]
  }
 ]
}